### ISSUE TITLE
Mauvais formatting d'une description par défaut d'une collective

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#112]
A la création d'une collective, la description par défaut est mal formatée:
![image](https://user-images.githubusercontent.com/59260805/74913910-d70d7b80-53c1-11ea-9d46-2586d006aba3.png)

Mettre

------
## Itinéraire:
**Altitude max** : 
**Dénivelé** : 
**Cotation** : 

## Matériel requis
------

**Comment by jnguiot** [comment]
C'est dû au fait qu'on a abandonné quill pour utiliser un éditor "markdown" comme sur github (#105).
Ce n'est donc plus du full WYSIWYG, mais c'est surement plus simple à éditer, et beaucoup plus simple à manipuler ensuite. 
Est-ce que la présence de tags markdown gènera beaucoup les utilisateurs?

**Comment by fberu** [comment]
Beaucoup de nos utilisateurs sont des "anciens" qui pour activer un compte auront besoin d'une doc.
Donc je te laisse imaginer si on leur met du markdown en plein milieu :sweat_smile:

**Comment by jnguiot** [comment]
Ok, on va voir si il y a des éditeurs full wysiwyg en markdown. Mais je ne pense pas qu'on reviendra à quill :)

**Comment by fberu** [comment]
Corrigé
