### ISSUE TITLE
[Import CSV] Le nombre de places par internet peut être optionnel

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#122]
Le nombre de places par internet est un champ optionnel. Aujourd'hui, lors de l'import d'une collective avec une valeur vide, l'erreur retournée est 
> Impossible d'importer la ligne 4: [ValueError] invalid literal for int() with base 10: '' OrderedDict([('nom_encadrant', 'François Béruard '), ('id_encadrant', '740019870006'), ('unknown', 'jjjjjj'), ('debut1', 'Monday 10 February 2020'), ('debut2', '10/2/20 7:00'), ('fin1', 'Monday 10 February 2020'), ('fin2', '10/2/20 7:00'), ('debut_internet', '3/2/20 7:00'), ('fin_internet', '9/2/20 12:00'), ('pictogramme', ''), ('titre', 'Pleine lune au Col de Tulle'), ('secteur', 'Aravis'), ('carte_IGN', ''), ('altitude', '1920'), ('denivele', '670'), ('cotation', 'F'), ('distance', ''), ('observations', 'Sortie pleine lune en soirée'), ('places', '11'), ('places_internet', ''), (None, [''])])

La ligne en question
> François Béruard ,740019870006,jjjjjj,Monday 10 February 2020,10/2/20 7:00,Monday 10 February 2020,10/2/20 7:00,3/2/20 7:00,9/2/20 12:00,,Pleine lune au Col de Tulle,Aravis,,1920,670,F,,Sortie pleine lune en soirée,11,,

Ce problème n'est pas bloquant, un workaround existe: mettre 0 comme valeur

**Comment by Cyr-GHub** [comment]
Je veux bien m'occuper de ce bug qui ne m'a pas l'air trop compliqué.

Par défaut il y a 0 mais si on vire cette valeur et qu'on enregistre l'evenement on a une erreur lors de l'insertion en base car le champ est typé integer non nul.
Je propose dans la fonction validate_dates_and_slots de forcer à 0 si la valeur est nulle.
Mais cela me pousse a me poser la question suivante :

Est-ce que 0 inscrit par internet est équivalent à aucun inscrit ?
Si on doit faire la distinction alors il faut revoir le modele de données pour autoriser la valeur nulle pour le champ num_online_slots
Si 0 et nulle ont la même signification alors la correction précédente conviendrait.
A l'exception du message suivant qui s'affiche sur la description de l'évènement :
"Le nombre maximum d'inscrits par internet a été atteint". 
Il serait plus juste de remplacer le texte par :
"Il n'y a pas de limite définie pour le nombre d'inscrits par internet"
