### ISSUE TITLE
[Import CSV] Gestion de la 1ère ligne avec le titre des colonnes

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#124]
Lors de l'import csv, si la 1ère ligne contient le titre des colonnes, on a l'erreur
> Impossible d'importer la ligne 1: [ValueError] time data 'Date début de sortie format site collectives' does not match format '%d/%m/%y %H:%M' OrderedDict([('nom_encadrant', 'Encadrants'), ('id_encadrant', 'Numéro de licence'), ('unknown', ''), ('debut1', 'Date début'), ('debut2', 'Date début de sortie format site collectives'), ('fin1', 'Date fin'), ('fin2', 'Date fin de sortie format site collectives'), ('debut_internet', "Date de début \nd'inscription\n Internet"), ('fin_internet', "Date de fin \nd'inscription\n Internet"), ('pictogramme', 'Pictogramme'), ('titre', 'Titre'), ('secteur', 'Secteur'), ('carte_IGN', 'Carte IGN'), ('altitude', 'Altitude \n(en m)'), ('denivele', 'Dénivelé \n(en m)'), ('cotation', 'Cotation'), ('distance', 'Distance\n(en km)'), ('observations', 'Observations '), ('places', 'Nombre total\nde places'), ('places_internet', 'Nombre total\nde places Internet')])

Soit détecter que la 1ère ligne contient le nom des colonnes
Soit rendre obligatoire la présence de cette ligne et commencer le traitement des données à partir de la 2ème ligne

**Comment by jnguiot** [comment]
On peut le faire, mais dans ce cas, il vaut mieux changer le nom des colonnes. Ca  te va?

**Comment by fberu** [comment]
Le plus simple ne serait pas de ne pas tenir compte de la 1ère ligne ?

**Comment by fberu** [comment]
Fixé par #242
