### ISSUE TITLE
[Legal] Mise en page RGPD

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#133]
Sur la page des mentions légales et "Mentions relatives à l'utilisation de données personnelles", il y a un petit problème de mise en page sur "Edition d’une fiche collective": cela devrait être préfixé par "4. ". Et du coup "4. Accès aux données des encadrants" devenir "5. Accès aux données des encadrants"

**Comment by shaiton** [comment]
@fberu peux-tu relire ma dernière PR voir si elle correspond à ton attente ? Et donner ton avis pour intégration…
