### ISSUE TITLE
Détail d'une collective: titre trop gros

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#138]
Dans le détail d'une collective, réduire la taille du titre. Un titre trop long prend trop de place.

![image](https://user-images.githubusercontent.com/59260805/76529254-572f7a00-6472-11ea-90ec-f700243825e2.png)

**Comment by jnguiot** [comment]
Si le titre est encore trop gros, je te laisserais me donner la taille que tu souhaites.

**Comment by jnguiot** [comment]
(je l'ai réduit de 30%)

**Comment by fberu** [comment]
Parfait!
