### ISSUE TITLE
Validation des dates d'inscriptions aux collectives

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#159]
Suite à #131 :
- la date de début des inscriptions par internet doit être inférieure à la date de début de la collective: aujourd'hui il n'y a pas de vérification
- la date de fin des inscriptions doit être inférieure à la date de début de la collective: aujourd'hui c'est la date de fin de la collective qui est vérifiée

**Comment by gdaviet** [comment]
@fberu Il y a eu dans le passé des collectives pour lesquelles le second critère n'était pas respecté (pas pour des "vraies" sorties mais choses au long cours du type validation de compétences)

**Comment by fberu** [comment]
@gdaviet oui effectivement mais c'était une utilisation détournée du but premier du site des collectives. Comme pour les achats groupés (ex: DVA, pelle, sonde).

Je propose dans un 1er temps de rester sur le but premier du site et donc d'implémenter les demandes de ce ticket. Le reste fera l'objet d'une évolution:
- validation des compétences: https://trello.com/c/F6H3e8i0
- achat groupé: https://trello.com/c/Q4pXMyIU
