### ISSUE TITLE
Changement d'encadrant: pas de filtre sur l'activité dans laquelle l'encadrant peut encadrer

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#173]
Lorsque je souhaite modifier l'encadrant d'une sortie, modifier l'encadrant d'une sortie, ou ajouter un encadrant, la liste des encadrants proposés n'est pas filtrée sur l'activité dans laquelle l'encadrant peut encadrer.
ie, un encadrant trail pourra devenir encadrant d'une collective d'alpinisme.

Edit: Un administrateur peut (à tort!) aussi être encadrant

**Comment by gdaviet** [comment]
C'est n'est pas un bug, comme précisé sur la PR; cela permet le workflow multi-activité.

**Comment by gdaviet** [comment]
Pour l'admin, on avait convenu de laisser ce fonctionnement pour l'instant. On peut changer les droits, cela voudra dire que l'admin ne pourra plus créer de sorties pour lui même non plus (ce qui serait normal, je suis d'accord avec toi sur cela). Mais c'est une changement de spécifications.

**Comment by fberu** [comment]
alors note pour moi-même la prochaine fois: ne pas avoir de conclusion sans au préalable fait un test avec un utiisateur non admin!

Ok pour rester comme ça pour l'admin: il peut mettre n'importe quelle activité, n'importe quel encadrant.

Avec un encadrant:
- Il ne peut pas se supprimer de sa sortie +1
- Il peut ajouter un autre encadrant, mais il n'y a aucun filtre sur le type d'activité. J'ose la question: bug ? :P 

Avec le nouvel encadrant ajouté:
- Il peut modifier la sortie créée par le 1er encadrant. Discutable à moyen terme. A discuter avec les encadrants. Laissons comme ça
- Il ne peut pas se supprimer de la sortie +1
- Il peut ajouter un autre encadrant, mais il n'y a aucun filtre sur le type d'activité
- Il peut supprimer l'encadrant qu'il ajoute +1
- Lorsqu'il tente de supprimer le 1er encadrant, l'erreur suivante s'affiche: "Encadrant(s) invalide(s) pour cette activité". Je trouve le message peu explicite. A priori parce que l'encadrant qui reste n'est pas autorisé à encadrer dans cette activité. Mettre un message plus explicite: "Au moins un des encadrants n'est pas habilité à encadrer dans cette activité. Si le problème persiste, contacter le responsable de l'activité"

Avec un responsable d'activité:
- il peut modifier la sortie
- il peut modifier les encadrants, dont supprimer l'encadrant initial
- même remarque que précédemment avec le message d'erreur "Encadrant(s) invalide(s) pour cette activité" peu explicite

**Comment by gdaviet** [comment]
Merci @fberu  pour les retours !
J'ai mis un message d'erreur plus explicite sur la PR #176 qui ajoute la notion de leader responsable.

Sinon:
> Il peut ajouter un autre encadrant, mais il n'y a aucun filtre sur le type d'activité. J'ose la question: bug ? :P

Oui c'est toujours le problème de l'oeuf et de la poule: si on veut que l'encadrant puisse ajouter une activité B qu'il ne peut pas encadrer à la sortie, il faut d'abord qu'il puisse ajouter un encadrant pour l'activité B. Donc il faut qu'ai aie accès à une liste non filtrée.
Cas concret: un encadrant ski de rando "X"  et un encadrant "Y" veulent reproduire http://m.skitour.fr/sorties/sortie.php?id=96919 . X ne peut créer que des sorties ski de rando, donc initialement la liste des activités disponibles dans le formulaire se limite à "Ski de rando". En revanche, une fois qu'il a ajouté Y à sa sortie, la liste des activités possibles devient ["Ski de rando", "Slackline"], et dans un futur proche il pourra cocher les deux.
Pour l'instant je t'accorde que l'intérêt est limité puisqu'en pratique on autorise pas encore la création de sorties multi-activité (sauf bug :p ), mais c'est en anticipation du future workflow. 

> Il peut modifier la sortie créée par le 1er encadrant. Discutable à moyen terme. A discuter avec les encadrants. Laissons comme ça
Oui tous les encadrants ont les mêmes droits d'édition. Si on veut un "sous-encadrant", ce sera une autre option, la même que pour les encadrants non-diplomés. Éventuellement on pourra donners des droits spéciaux à l'encadrant responsable, à définir.

**Comment by fberu** [comment]
ok pigé!
Du coup on limite ce ticket à mettre un message d'erreur plus explicite à la place de "Encadrant(s) invalide(s) pour cette activité".
Fait dans #176 ("Aucun encadrant valide n'a été défini pour l'activité ..."). Je ferme donc ce ticket
