### ISSUE TITLE
Sortie multiactivité affichée à tort

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#175]
Sur collectives2.cafannecy.fr, un encadrant ski de rando, randonné raquette et randonnée montagne a créé une sortie ski de rando.
La sortie s'affiche malheureusement en multiactivité, avec ces activités.

Sortie https://collectives2.cafannecy.fr/event/13

![image](https://user-images.githubusercontent.com/59260805/78357937-a3259880-75b2-11ea-9881-5a25784aacf8.png)

**Comment by gdaviet** [comment]
@fberu tu as moyen de reproduire sur le serveur de test? Que se passe-t-il si tu édites la sortie? Pour l'instant je ne vois pas ce qui dans le code ce qui pourrait conduire à ca

**Comment by fberu** [comment]
Je confirme, je n'arrive pas à reproduire sur le site de test :)
Je ferme le ticket
