### ISSUE TITLE
Difficultés pour laisser le menu affiché et cliquer sur un lien

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#181]
Plusieurs personnes remontent des problèmes pour interagir avec le menu: une fois qu'ils ont cliqué sur le sandwich, il leur arrive fréquemment que le menu déroulant disparaisse.

Une personne qui a l'habitude de ce type de menu n'aura jamais le problème. Par contre une personne peu habituée, peut rapidement "bloquer" dessus.

Personnellement je n'ai pas le soucis sauf en allant lentement, en cherchant les angles du sandwich.

**Comment by jnguiot** [comment]
Oui, en fait, c'est dû à quelques pixels qui apparaissent entre le bouton et le menu. Quand la souris quitte le bouton, ca cache le menu. Je vais regarder pour un fix
