### ISSUE TITLE
Pas de "limite" de largeur du texte de la description d'une sortie

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#184]
Lorsqu'on édite une collective, qu'on met un mot très long, le mot déborde lorsqu'on consulte la collective.

Dans cet exemple l'encadrant a fait un mot extrêmement long avec que des P.
Sur l'écran d'édition de la collective, l'affichage est ok
![image](https://user-images.githubusercontent.com/59260805/79066964-15d1fa80-7cbc-11ea-958c-cfa8e7c4ad80.png)

Par contre lorsqu'on consulte la collective, ça déborde
![image](https://user-images.githubusercontent.com/59260805/79066976-297d6100-7cbc-11ea-9eb6-987b8a493937.png)

**Comment by jnguiot** [comment]
Y'en a qui font vraiment du monkey testing <_<...

**Comment by jnguiot** [comment]
Pour bien tester la correction: faire une purge du cache (ctrl+f5)
