### ISSUE TITLE
Date affichée du x au y alors que la sortie n'est que sur un seul jour (pb Safari ?)

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#185]
Sur collectives2.cafannecy.fr, sur la page listant les sorties, les soirées https://collectives2.cafannecy.fr/event/9 et https://collectives2.cafannecy.fr/event/37 sont affichées allant du x mai 2020 au y mai 2020 alors que la soirée est de 19h à 22h.

Ce problème ne semble arriver que sur Safari.

Affichage dans la liste (problème):
![image](https://user-images.githubusercontent.com/59260805/79075987-be9d4b80-7cf6-11ea-9f8c-a43036e7e106.png)

Détail de la sortie Trail (ok)
![image](https://user-images.githubusercontent.com/59260805/79075997-d1178500-7cf6-11ea-99a5-50d88b9c9929.png)

Données saisies (ok)
- Trail
![image](https://user-images.githubusercontent.com/59260805/79075999-d5dc3900-7cf6-11ea-90a1-1864acc30a4f.png)
- Rando
![image](https://user-images.githubusercontent.com/59260805/79076032-1936a780-7cf7-11ea-80dc-be7e79b2d38a.png)

**Comment by jnguiot** [comment]
@gdaviet tu pourras regarder? Sans safari, j'aurais du mal à traiter ce bug.

**Comment by gdaviet** [comment]
Oui je peux reproduire le bug, je vais regarder ca.
