### ISSUE TITLE
Les coordonnées du groupe ne comprennent pas ceux des leaders

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#187]
Dans Coordonnées du groupe du tableau Administration d'une sortie, seuls les coordonnées des participants sont indiqués. @fberu : faudrait-il rajouter aussi les coordonnées des encadrants (utile en cas de sortie avec plusieurs encadrants)

**Comment by fberu** [comment]
L'idée des coordonnées mails et téléphone est de permettre de joindre facilement les participants à une sortie pour les avertir d'un changement. Facilement = copier / coller :)
Lorsqu'il y a co-encadrement, généralement les encadrants se sont entendus avant de communiquer aux inscrits. Et ils connaissent leurs coordonnées mutuelles.

Effectivement nous pourrions ajouter les coordonnées des encadrants dans la liste mais je vois plus d'effets de bord et complexité:
. je suis l'encadrant A, mes coordonnées ne doivent pas apparaître. Par contre ceux de l'encadrant B, oui
. inversement, je suis B, je ne dois pas voir A
. en tant que A, je me suis déjà entendu avec B, peut être n'ai-je pas envie de lui envoyer un sms. Donc je vais chercher son numéro dans la liste

Je serais plus d'avis de rester en l'état

**Comment by jnguiot** [comment]
Ok, donc je ferme.
