### ISSUE TITLE
Le filtre des activités ne s'affiche pas sur Safari / MacOS

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#205]
Le filtre des activités ne s'affiche pas sur Safari / MacOS
![image](https://user-images.githubusercontent.com/59260805/79684249-158fad00-8230-11ea-9f0c-26a87cbfcb83.png)

(c'est ok sur Safari sous iOS)

**Comment by gdaviet** [comment]
Pas de soucis chez moi  -- il faut peut être que tu rafraichisse le cache de ton navigateur (appuyer sur rafraichir à droite de la barre d'adresse en maintenant "Maj" appuyé)

**Comment by fberu** [comment]
Merci @gdaviet ! L'encadrant m'a confirmé que c'était bien cela.
Je ferme :)
