### ISSUE TITLE
Fiche imprimable d'une collective: ouvrir une nouvelle fenêtre

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#208]
Demande d'évolutions des encadrants: ouvrir une nouvelle fenêtre lorsqu'on souhaite voir / imprimer la fiche imprimable d'une collective

**Comment by gdaviet** [comment]
Au cas où, ils ont essayé les raccourcis standard pour cela? Genre clic du milieu ou "Command+clic" sous OSX?

**Comment by fberu** [comment]
@gdaviet malheureusement les "anciens" ont du mal avec les raccourcis clavier ;)
