### ISSUE TITLE
Test failling 

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#217]
On a cette erreur dans les tests récemment:
```     "validators": Email(message="Format d'adresse invalide"),
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/wtforms/validators.py:332: in __init__
    raise Exception("Install 'email_validator' for email validation support.")
E   Exception: Install 'email_validator' for email validation support.```

**Comment by jnguiot** [comment]
Il faut donc installer  `email_validator`

**Comment by playerla** [comment]
Hello,
I Just deploy on Heroku and get this error (but it work on local docker development)

Seems we are not alone https://stackoverflow.com/questions/61356834/wtforms-install-email-validator-for-email-validation-support.

Would it be a missing dependency ?
