### ISSUE TITLE
Vocabulaire états des collectives

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#231]
Actuellement l'état des collectives est Annulée, En attente, Confirmée.

Pour éviter certaines confusions et dans l'éventualité future d'un process de validation, modifier les états comme suit:
- Annulée -> Annulée
- En attente -> Projet
- Confirmée -> Au programme

En effet à terme l'état Confirmée pourrait indiquer que la sortie au programme est confirmée et aura lieu

En profiter aussi pour distinguer le titre d'une collective Annulée d'une collective en Projet / En attente. Aujourd'hui les 2 apparaissent en blanc majuscule sur fond rouge. Mettre Projet en blanc majuscule sur fond orange
![image](https://user-images.githubusercontent.com/59260805/80316462-55413080-87fe-11ea-89ad-a53d99aa79b5.png)

**Comment by shaiton** [comment]
J'attaque cette tâche ce weekend (hum, dimanche).
Si pas de nouvelle d'ici mercredi et que quelqu'un veut la traiter, pas de problèmes.

**Comment by jnguiot** [comment]
Vu que le vocabulaire n'a pas l'air de gêner à l'utilisation, je ferme.
