### ISSUE TITLE
"Erreur event inexistant" alors que l'évènement est bien dans la liste des évènements

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#264]
Parfois, en souhaitant regarder les détails d'un évènement qui apparait dans la liste, on a une erreur event inexistant. Ca a l'air lié à l'évènement vu que ca se reproduit tout le temps pour le même évènement.

**Comment by jnguiot** [comment]
Ce bug se produit pour les collectives contenant un espace ou un tiret dans leur titre. En effet, lors de l'extraction des variables dans l'url, event_id va du début de la string jusqu'au dernier tiret, et non jusqu'au premier. 

Ainsi:
`21-debutant-tour-des-monts-rampon-et-rampignon-veyrier` devient `event_id = '21-debutant-tour-des-monts-rampon-et-rampignon'` et `name = 'rampignon'`

**Comment by jnguiot** [comment]
Bug introduit par  #257

**Comment by shaiton** [comment]
ah bien vu, je l'ai souvent eu mais je n'avais pas fait le lien avec un caractère spécial
