### ISSUE TITLE
Le symbole ":" crée un lien incorrect dans les descriptions 

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#266]
**Scénario de reproduction:** insérer la chaine de caractère `bb:aaa` dans une description d'évènement et enregistrer.
**Comportement observé:** un lien hypertexte est inséré sur `bb:aaa` avec comme url `bb:aaa`
**Comportement attendu:** un lien hypertexte ne devrait être créé que pour les protocoles http et https

**Comment by jnguiot** [comment]
C'est l'URI_REGEX qui capture quelque chose qu'il ne devrait pas: https://github.com/Club-Alpin-Annecy/collectives/blob/c24361d9950af132cc886d65d686bcd06b8e22cf/collectives/utils/render_markdown.py#L11

**Comment by gdaviet** [comment]
Oui la regex capture des URI au sens plus général du terme, mais je suis d'accord qu'il est plus pertinent de restreindre à http et https
