### ISSUE TITLE
"Page inconnue: /favicon.ico"

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#268]
Après avoir afficher une fiche collective, la prochaine page du site que sera chargé affichera le message flash `Page inconnue: /favicon.ico`.

C'est dû à la fiche collective qui tente de charger un favicon qui n'existe pas, qui enregistre donc une erreur qui est affichée à la prochaine page.

**Comment by gdaviet** [comment]
@jnguiot ce bug est assez pénible à l'usage, je ne me souviens plus si tu avais un fix?
Je proposerais bien de remettre une vraie 404 plutôt qu'une 302+flash
