### ISSUE TITLE
Datepicker 

### ISSUE THREAD

**Issue by shaiton** [Club-Alpin-Annecy/collectives#27]
tail.DateTime v.0.4.14 datetimepicker does not use the current time. Always use default to 00:00:00 unless we change the time manually.

Not a big issue, and we should probably open this on the upstream project.

**Comment by fberu** [comment]
Ticket de fin 2019. Depuis des modifications ont été faites sur les datepicker. Dorénavant c'est bien l'heure courante qui est affichée (à 5min prêt)

Screenshot fait à 12h17
![image](https://user-images.githubusercontent.com/59260805/79066373-b4a82800-7cb7-11ea-91da-c21e9de83be2.png)

Pour moi on peut donc fermer le ticket. Ok pour toi @shaiton ?

**Comment by shaiton** [comment]
Ça a beaucoup changé depuis mes dernières propositions (et vacances).
J'attends qu'il pleuve pour racrocher le vagon…
