### ISSUE TITLE
Afficher son numéro de licence dans le profil Utilisateur

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#271]
Afficher son numéro de licence dans le profil Utilisateur.

Remplacer la 1ère ligne
![image](https://user-images.githubusercontent.com/59260805/81505547-4d9a8500-92f0-11ea-82fa-df5e3b8ae87e.png)

Par:

- Licence: {numéro de licence}
- Catégorie: {nom de la catégorie}

**Comment by jnguiot** [comment]
Ca te va si on fait: 
**Licence : ** 740000112233 Catégorie T1

Ca économise une ligne :)

**Comment by fberu** [comment]
Tu aimes bien le compact toi! :)

**Comment by shaiton** [comment]
Ça serait bien d'informer l'utilisateur sur ce que signifie la catégorie, non ? (au moins au survol de la souris (super l'ergo avec une tablette))
