### ISSUE TITLE
Lien direct vers un numéro de page: le bas de la nouvelle page s'affiche plutôt que le haut

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#288]
Dans la liste des collectives, lorsqu'on navigue dans les pages:

- le lien suivant ou précédent change bien la page et mets le focus en haut de la page
- par contre si on sélectionne directement un numéro de page, le focus reste en bas de page

A noter que sur la liste des adhérents (menu Administration), ce problème n'apparaît pas

**Comment by shaiton** [comment]
Oui je confirme le problème, et c'est assez agaçant quand peut d'entrées sont sur la page, on dirait que la page est vide.
Bon, j'ai commencé mais le js n'est pas naturel pour moi, je devrai pouvoir proposer un truc cette aprem
