### ISSUE TITLE
[Activation compte] Erreur 500 quand la licence n'a pas été renouvelée

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#295]
Lorsqu'un utilisateur tente d'activer son compte alors que sa licence n'a pas été renouvelée, une erreur 500 est générée

**Comment by gdaviet** [comment]
@fberu as tu plus de détails sur cette erreur? (à quel stade de l'activation se produit-elle, avant ou après le mail de confirmation?)

**Comment by jnguiot** [comment]
Je n'ai rien vu dans les logs qui ressemblerait à une erreur sur ce genre de problème.

**Comment by shaiton** [comment]
@fberu impossible de reproduire l'erreur.
Peux-tu nous fournir en pv son numéro de licence et nous autoriser à le contacter au besoin ?

Normalement il doit obtenir le message suivant 
« Licence inexistante ou expirée ».
