### ISSUE TITLE
La dupplication d'une collective devrait interdire le même sujet

### ISSUE THREAD

**Issue by shaiton** [Club-Alpin-Annecy/collectives#304]
Actuellement on peut duppliquer une collective et valider exactement la même description :
- on devrait interdire de duppiquer une collectives avec un sujet identique, ou alors explicitement modifié le sujet avec que l'encadrant l'édite lors de la dupplication ( « copie - < sujet initial > »)

aussi, je n'ai pas vérifié mais je suppose que les inscrits sont duppliqués également ? et notifié ?

**Comment by fberu** [comment]
Pas d’accord. 
La principale personne, si ce n’est la seule et unique personne qui s’en sert actuellement, c’est moi 🙂

Chaque semaine, tout l’année, 2 séances de PPG par semaine, qui chacune ont le même titre. 1 fois par mois j’en duplique 4-5. Les titres restent inchangés, seule la description peut varier. 

Demain, peut être, aurons-nous aussi les créneaux d’escalade l’hiver. 

Autre besoin. Une collective est créée. Toutes les places sont prises. Un deuxième encadrant peut alors dupliquer la collective pleine et donc faire un 2ème groupe. 

Enfin, il n’est pas rare qu’une Tournette soit fait plusieurs fois dans la même année. 

Pour répondre à tes interrogations, lors d’une duplication, seules les infos de la collective sont dupliquées. Tu arrives alors dans une fenêtre d’édition. Et la collective est réellement dupliquée que lorsque tu l’enregistres. 
Lors d’une duplication les inscrits ne sont pas « dupliqués » et ne reçoivent donc pas de notification

**Comment by shaiton** [comment]
ok si tu veux.
Mais si je reformule, la description ou le sujet devraient différer.
Dans la description j'entends les dates

Si tu duppliques sans modifier, tout sera identique. Si tu dois faire un second groupe, hum, alors dans la description appeler second groupe ?

Parce que avec deux collectives *identiques* les utilisateurs ne vont pas comprendre et s'inscrire aux deux…

**Comment by fberu** [comment]
Regarde mes séances de PPG de semaine pro et semaine suivante. Tout est identique car même heure, même lieu, même contenu chaque semaine. Seule la date change

> Si tu duppliques sans modifier, tout sera identique. Si tu dois faire un second groupe, hum, alors dans la description appeler second groupe ?

Si la collective est même titre, même description, même date, même heure ce sera l'encadrant qui changera (là dessus on pourrait éventuellement rajouter une contrainte. Si c'est un second groupe, effectivement ce sera à préciser

> Parce que avec deux collectives identiques les utilisateurs ne vont pas comprendre et s'inscrire aux deux…
Pour ce point il faudra rajouter de la robustesse côté site, et interdire une inscription à deux collectives ayant lieu au même moment (date et heure)
