### ISSUE TITLE
Affichage impréci de la liste des participants (email, téléphone)

### ISSUE THREAD

**Issue by shaiton** [Club-Alpin-Annecy/collectives#314]
Plusieurs problèmes :
 - on indique coordonées du groupe, mais il ne s'agit que des inscrits et non pas des encadrants (on peut très bien avoir un coencadrant qu'on ne connait pas…) la liste d'email est pratique pour communiquer à tous. Ajouter les encadrants serait intéressants (filtrer l'encadrant faisant l'action)
 - certains inscrits n'ont pas de numéro de téléphone. Il faudrait le préciser.

Voyer le cas d'une collective  avec 15 inscrits. Vous pensez communiquer à tout le monde, ben non… raté.

**Comment by fberu** [comment]
L'objectif de ces champs est que l'un des encadrants puissent contacter facilement les inscrits. Les encadrants ne sont pas dans cette liste car on suppose qu'ils se seront entenuds entre eux avant de communiquer (sinon ce n'est plus du co-encadrement!). Raison pour laquelle ils n'apparaissent pas dans le liste et raison pour laquelle on ne le fera pas.

Pour les adhérents n'ayant pas renseigné de téléphone. J'ai envie de dire que c'est leur choix!

En conclusion, pour moi ce ticket est une question de wording.

- "Coordonnées du groupe" -> mettre à la place qqch comme "Contacter les inscrits"
- si certains n'ont pas renseigné leur numéro de téléphone, mettre un warning sous le champ "Liste téléphonique": "Attention, tous les inscrits n'ont pas renseigné leur numéro de téléphone"

**Comment by shaiton** [comment]
oui je suis d'accord c'est bien sur la formulation, je ne demandais pas d'ajouter les encadrants. Mais c'est facile de se dire « je contacte tout le monde » mais en fait j'en oublie.

Pour le côté numéros de téléphones non renseigné, on devrait pouvoir construire la liste des personnes qui n'ont pas de numéro (ça évitera de chercher nous-même à la main)

**Comment by jnguiot** [comment]
Pour les inscrits sans numéro: ce n'est plus permis
