### ISSUE TITLE
[UI] Version du site génère un lien

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#318]
La nouvelle UI génère un lien sur la version du site
![image](https://user-images.githubusercontent.com/59260805/85171759-e7e6d480-b26f-11ea-91b6-3f5f6ed9d136.png)

**Comment by gregone** [comment]
@fberu ca a été ajouté par @jnguiot dans https://github.com/Club-Alpin-Annecy/collectives/pull/300 Je n'ai fait que le transférer sur le nouveau footer

**Comment by jnguiot** [comment]
Oui, et c'est vachement pratique pour le déploiement. C'est pas un bug ;)

**Comment by fberu** [comment]
ok ça marche.
En fait, le -67- n'ayant pas de lien, c'est ça qui m'a fait créer un ticket
