### ISSUE TITLE
[UI] Boutons "Enregistrer" et "Importer" non centrés

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#319]
Lorsqu'on édite une collective, le bouton "Enregistrer" n'est pas centré
Idem pour le bouton "Importer" pour l'import CSV
A moins que ce ne soit fait exprès ?

![image](https://user-images.githubusercontent.com/59260805/85172054-90953400-b270-11ea-9422-e732802517b6.png)

**Comment by gregone** [comment]
J'ai enlevé l'alignement centré sur les formulaires, d'ou le décalage a gauche. 

Je previous de refaire enormément de changements sur ces formulaires, donc il faut considerer ce layout comme temporaire. 

Par contre l'alignement a gauche des champs et des boutons est un peu [un standard au niveau usabilité](https://uxplanet.org/buttons-alignment-policy-a26de4ce0c70) donc je ne vois pas ou est le problème , ou en quoi c'est un "bug" :)

**Comment by fberu** [comment]
> je ne vois pas ou est le problème , ou en quoi c'est un "bug" :)

D’où ma remarque « A moins que ce ne soit fait exprès ?» 😉

Merci pour tes retours. Je ferme
