### ISSUE TITLE
Datepicker anchoring

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#32]
All datepickers seem to be anchored to the page, not to the field
![image](https://user-images.githubusercontent.com/59260805/71544451-dd621700-297f-11ea-95e1-0b0184386eb7.png)

**Comment by jnguiot** [comment]
Yes, I have reproduced this behavior.
It seems to be linked to the datepicker we are using: https://github.pytes.net/tail.DateTime/

**Comment by alkino** [comment]
More over, the hour is useless. What do you think about these one for example: https://www.cssscript.com/demo/date-range-picker-lightpick/

**Comment by jnguiot** [comment]
C'est très sympa, mais ca utilise jQuery. Pour le moment, j'ai évité son utilisation pour rester sur du [vanillaJS](http://vanilla-js.com/)...
Sinon, ce bug est peu problématique, et on a plutôt donné la priorité aux interface tout public qu'aux interface d'administration. On s'y penchera plus tard :)

**Comment by shaiton** [comment]
Ce bug je ne l'avais pas reproduit.

Côté heure d'ouverture ou fermeture des inscriptions, on peut la cacher avec le datepicker actuel c'est un configuration. Par contre, c'est sûrement nécessaire à garder (genre ouverture à 8h42 pour tromper tout le monde, et fermeture le vendredi à 18h afin de limiter les inscriptions en paralèle par le forum)

**Comment by fberu** [comment]
Corrigé par #191
