### ISSUE TITLE
Ergo incompatible tablette/smartphone : impossible de désinscrire un inscrit

### ISSUE THREAD

**Issue by shaiton** [Club-Alpin-Annecy/collectives#323]
Sur téléphone (écran tactile) il est impossible de supprimer un inscrit de la liste.
D'une manière  général, le statut css hover ne devrait être *que* pour du visuel.

**Comment by gregone** [comment]
C'était deja le cas avant mes changements. Mais je peux m'occuper de ça.

**Comment by shaiton** [comment]
ah effectivement je n'ai pas pensé à tester sur test.collectives (après tes modifs) c'est sur l'instance de prod ce ticket :)

**Comment by fberu** [comment]
@shaiton , tap une première fois sur son prénom, le bouton refuser apparaît. Et tu peux alors cliquer sur refuser 🙂

**Comment by jnguiot** [comment]
On peut à présent désinscrire sur la liste des enregistrements
