### ISSUE TITLE
Impossible d'accéder aux menus sous Safari / MacOS

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#324]
Retour d'un utilisateur, avec la nouvelle ergo, il n'est plus possible d'accéder aux menus (gauche et droite) depuis Safari / MacOS

**Comment by shaiton** [comment]
ahah, super on a identifié un nouvel utilisateur pour les tests de non reg sur l'instance de... test.

(Zen, Soyons Zen)

**Comment by gdaviet** [comment]
Tu peux lui demander la version? Chez moi ca marche bien.
Par contre il faut cliquer dessus, alors qu'avant c'était juste au hover...


Sinon peut être une histoire de cache, essayer de cliquer sut le bouton "Actualiser" à droite de la barre d'URL en maintenant "Shift" appuyé

**Comment by gregone** [comment]
@fberu oui maintenant il faut cliquer. Et ça j’avais testé sur safari/macOS et ça fonctionne. Tu peux confirmer?

**Comment by fberu** [comment]
Pas de retour de sa part. Et fonctionne bien sous iOS. Je ferme
