### ISSUE TITLE
Un emoji dans la description génère une erreur 500

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#363]
Lorsqu'on saisi un emoji dans la description d'une collective, cela génère une erreur 500 lors de l'enregistrement.
Soit "accepter" les emoji, soit intercepter l'utilisation d'emoji en les retirant

**Comment by shaiton** [comment]
Pour toi l'emoji, c'est l'icône en UTF-8, ou le module d'édition qui permet d'en saisir une ? (En gros, d'où est-ce que tu la saisie ?)
Perso je ne vois pas comment en ajouter… (j'imagine que c'est en utf-8 du coup de ton navigateur)

**Comment by gdaviet** [comment]
D'après mes tests en local cette solution fonctionne: https://docs.sqlalchemy.org/en/13/dialects/mysql.html#unicode
Ajouter `?charset=utf8mb4` à la fin de la variabke `SQLALCHEMY_DATABASE_URI`, e.g. `"mysql+pymysql://root:@localhost/test?charset=utf8mb4"`

@jnguiot tu aurais moyen de tester ca?

**Comment by jnguiot** [comment]
Je confirme le fix sur test.collectives.cafannecy.fr
TODO:
* Modifier la configuration de la production
* Compléter la documentation

**Comment by jnguiot** [comment]
BTW, j'ai changé les labels : une erreur 500 est pour moi toujours un bug. Ca veut dire qu'au mieux, il y a un cas d'erreur qu'on ne gère pas bien!

**Comment by jnguiot** [comment]
Conf et doc modifiée.
