### ISSUE TITLE
Trier les logs serveurs par date décroissante

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#368]
Dans le menu Logs du serveur, trier les logs par date décroissante. Aujourd'hui il ne semble pas y avoir d'ordre

**Comment by jnguiot** [comment]
Pour être honnête, j'ai fait exprès de passer peu de temps sur cette interface qui reste à destination des dev et des admins. D'où son aspect austère.

Si ça doit être fait, le mieux c'est que ca serve d'exercice à un nouveau: je rajoute le tag good first issue.
