### ISSUE TITLE
Message plus explicite lors d'une tentative de récupération de compte inexistant

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#395]
Beaucoup de personnes ne comprennent pas qu'elles doivent au préalable créer leur compte sur le site des collectives. Du coup elles tentent (a priori) se connecter sur les collectives avec leurs identifiants de la fédé. Comme cela ne fonctionne pas, elles tentent une récupération de compte. Comme le compte n'existe pas, le message

> Aucun compte n'est associé à ces identifiants

est affiché et les gens sont perdues -> hotline.

Une partie de la confusion peut venir du fait que les gens confondent compte fédé et compte collectives. Le site leur dit qu'aucun compte ne correspond alors qu'ils viennent de rentrer leurs email/license fédé, du coup ils doivent se dire qu'ils ont rentré un mauvais truc ou qu'il y a un problème niveau fédé, du coup hotline. Je pense qu'il faudrait mettre en exergue le fait que ce soit ok niveau fédé mais qu'il doivent aussi créer aussi un compte "collectives".

Et donc plutôt afficher le message

> Vos identifiants correspondent à une license valide mais vous n'avez pas encore activé votre compte collective. Veuillez cliquer sur le lien en bas de page pour procéder à sa création

lorsqu'une personne tente de récupérer un compte qui n'existe pas

**Comment by jnguiot** [comment]
Suite au fix de Gilles, et l'absence de cas rencontré dernièrement, je propose de clore.
