### ISSUE TITLE
Faire apparaître plus explicitement les inscrits en attente de paiement sur l'en-tête d'une collective

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#429]
Sur une collective avec paiement, les adhérents inscrits en attente de paiement sont fort logiquement comptés dans le nombre d'inscrits.
Or "on ne les voit pas".

Dans cet exemple, la collective ne compte qu'une place et il y a un inscrit en attente de paiement.
![image](https://user-images.githubusercontent.com/59260805/118304081-7f878e00-b4e6-11eb-8cd4-6b9a00b6a96d.png)

Le 0/1 avec "Complet" à côté pourrait paraître déroutant.

L'idée de ce ticket serait de:

- soit afficher les inscrits en attente de paiement comme tout inscrit
- soit afficher les inscrits en attente de paiement avec peut être une * ou autre indiquant son statut en attente
- soit afficher à côté du 0/1 un "1 en attente de paiement"
- soit ...

**Comment by gdaviet** [comment]
@fberu je suis parti sur la solution 3, cf #437
