### ISSUE TITLE
Pb d'affichage de la 1ère page de la liste des paiements

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#458]
Actuellement sur la prod, en filtrant sur l'activité escalde, la page "Liste des paiements" (https://collectives.cafannecy.fr/payment/list), la 1ère page n'affiche pas tout, il y a un grand espace blanc avant d'atteindre le bas de page

**Comment by jnguiot** [comment]
On n'a pas accès à la page. Peux-tu reproduire le bug sur test ou nous faire une capture d'écran?

**Comment by fberu** [comment]
@jnguiot je viens de vous donner les accès sur la prod. Plus simple ^^

**Comment by jnguiot** [comment]
A noter que ce problème se produit lorsqu'on passe d'une liste sans filtrage pour une liste sans filtrage. Quand on clique pour la sélection de l'activité, celà tente de charger une liste filtrée sur "None", ce qui renvoie une erreur 500 par le serveur et pose problème par la suite.
Il suffit de mieux protéger cette ligne des TypeError https://github.com/Club-Alpin-Annecy/collectives/blob/b309b916f4b62102b5a84ddf23b67f256039874d/collectives/utils/payment.py#L49
