### ISSUE TITLE
Erreur lors du reimport d'un extract de la BDD sous mysql

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#545]
Lorsque je tente d'importer un extract journalier de la BDD de prod sur un serveur mysql, j'ai les erreurs suivantes:

`ERROR 1170 (42000) at line 85: BLOB/TEXT column 'name' used in key specification without a key length`
-> table `config`, colonne `name`: workaround en mettant le type varchar(256)

`ERROR 3822 (HY000) at line 322: Duplicate check constraint name 'CONSTRAINT_1'.`
`ERROR 3822 (HY000) at line 700: Duplicate check constraint name 'CONSTRAINT_2'.`
-> concerne une petite dizaine de tables: les noms sont unique par table, mais pas par database: workaround en mettant un autre nom de contrainte

`ERROR 1064 (42000) at line 755: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PAGE_CHECKSUM=1 TRANSACTIONAL=0 COMMENT='Statistics on Columns'' at line 14`
-> concerne quelques tables: workaround: supprimer `'PAGE_CHECKSUM=1 TRANSACTIONAL=0 COMMENT='...'

`ERROR 1101 (42000) at line 920: BLOB, TEXT, GEOMETRY or JSON column 'Priv' can't have a default value`
-> table `global_priv`. Workaround: supprimer la default value sur la colonne 'Priv'

`ERROR 3554 (HY000) at line 1072: Access to data dictionary table 'mysql.index_stats' is rejected.`
`ERROR 3554 (HY000) at line 1076: Access to system table 'mysql.innodb_index_stats' is rejected.`
`ERROR 3554 (HY000) at line 1073: Access to system table 'mysql.innodb_table_stats' is rejected.`
`ERROR 3554 (HY000) at line 1251: Access to data dictionary table 'mysql.table_stats' is rejected.`
-> workaound: supprimer les tables

**Comment by jnguiot** [comment]
* Est-ce que les versions mysql de prod et chez toi sont bien les mêmes? 
* Concernant la base mysql, tu peux ne pas la réimporter, c'est inutile

**Comment by fberu** [comment]
Gilles m'a répondu sur le Slack. La BDD doit être sous MariaDB. Je clos ce ticket
