### ISSUE TITLE
Bug affichage Agenda Shabrasserie avec Firefox

### ISSUE THREAD

**Issue by oliv42** [Club-Alpin-Annecy/collectives#560]
Bonjour,

L'agenda n'est pas visible, on a un le message 'Firefox ne peut pas ouvrir cette page'.
Ici le lien qui corresponds au problème d'après Firefox: https://support.mozilla.org/fr/kb/page-erreur-reseau-xframe?as=u&utm_source=inproduct

Page concerné: https://www.cafannecy.fr/partager/le-bar

Bien cordialement

**Comment by jnguiot** [comment]
Merci pour le retour, cependant, ce github est uniquement lié au site des collectives: c'est une autre équipe qui s'occupe du site cafannecy.fr .tu peux contacter François à ce propos, @fberu . Cependant, je vais en parler sur le slack des outils numériques.

**Comment by fberu** [comment]
Bonjour @oliv42 , correction faite. Mais effectivement pas le bon GitHub.
On recherche du monde pour développer sur notre site des collectives. Est-ce que ça te dirait de rejoindre l'équipe ? On peux se voir un soir à la Shabrasserie pour en discuter de vive. Tu peux aussi contacter @jnguiot  ou @gdaviet pour plus d'infos techniques ou te montrer les 1ers pas.

François
