### ISSUE TITLE
Deux évènements accolés sont considérés comme en même temps

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#579]
### Conditions initiales:
* Un évènement A existe et un utilisateur Z y est inscrit. L'évènement est de 18h à 20h
* Un évènement B existe et est dans sa période d'inscription

### Comportement observé:
* L'utilisateur Z se voit refuser l’inscription au motif qui a déjà un évènement à ce moment

### Comportement attendu:
* L'utilisateur Z devrait pouvoir s''inscrire

**Comment by fberu** [comment]
J'ai plus ou moins constaté la même chose. A voir si c'est vraiment le cas.

- un événement A a lieu de 18h00 à 20h00
- un événement Z a lieu de 20h00 à 22h00

Un encadrant ne peut pas être encadrant sur les 2 événements. Cela lui indique qu'il encadre déjà une collective au même moment.

Si on met les événements comme ceci, tout fonctionne

- un événement A a lieu de 18h00 à 20h00
- un événement Z a lieu de 20h0**1** à 22h00

**Comment by gdaviet** [comment]
@fberu oui c'est codé comme ça actuellement. On peut facilement le changer pour autoriser l'overlap exact des heures de fin et de début : https://github.com/Club-Alpin-Annecy/collectives/pull/580
