### ISSUE TITLE
Le badge "liste d'attente" ne s'affiche pas 

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#604]
## Conditions initiales: 
version [v14.3](https://github.com/Club-Alpin-Annecy/collectives/releases/tag/v14.3)-26-g57b8ff0 suite au merge de #598 

## Scénario de reproduction
Créer une collective:
* Avec 7 places
* 0 places sur Internet
* 7 places en liste d'attente
Ex: https://test.collectives.cafannecy.fr/collectives/309-quermoz

## Comportement observé:
La collective est bien accessible qu'en liste d'attente. Cependant, il n'y a pas le badge ad-hoc sur la page d'acceuil

## Comportement attendu
Le badge sur la page d’accueil doit s'afficher si et seulement si la méthode d'inscription est la liste d'attente

**Comment by bbouffaut** [comment]
Bien vu, c'est un cas de figure que je n'avais pas envisagé (j'ai injustement pensé qu'une liste d'attente venait en "overhead" de la liste des inscrits).Je vais fix cela
