### ISSUE TITLE
Impossible de lier les inscriptions des écoles d'aventure à une collective

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#618]
Trois événements d'inscription existent actuellement sur le site afin de gérer les écoles d'aventure:

- https://collectives.cafannecy.fr/collectives/4460-ecole-daventure-groupe-des-experts-20222023
- https://collectives.cafannecy.fr/collectives/4461-ecole-daventure-groupe-decouverte-20222023
- https://collectives.cafannecy.fr/collectives/4462-ecole-daventure-groupe-des-trappeurs-20222023

Il est malheureusement impossible de créer une nouvelle collective en ayant l'une de ces 3 sorties comme restriction d'inscription

**Comment by gdaviet** [comment]
Tu peux préciser l'erreur ? Pour ma part j'arrive bien à les ajouter. Si tu ne les vois pas dans la liste c'est peut-être du à l'activité sélectionnée, coche "Multi-activité" pour tester 

<img width="1154" alt="Capture d’écran 2023-04-16 à 19 40 38" src="https://user-images.githubusercontent.com/57617656/232330670-a35d5916-3d08-4165-a46e-dd920c386429.png">

**Comment by fberu** [comment]
Effectivement, lorsque je sélectionne "multi activités", ces deux collectives apparaissent bien.
La collective sur laquelle cela ne fonctionnait pas https://collectives.cafannecy.fr/collectives/6321-ecole-daventure-randorientation-pour-les-groupes-des-aventuriers-et-des-experts pour laquelle j'ai pu faire les liens en cochant multi activités

Je crois que j'ai compris:

- si dans la collective mère, une ou des activités sont mises, alors la collective fille doit obligatoirement être d'une de ces activités
- si dans la collective mère aucune activité n'est mise, alors aujourd'hui il faut cocher "multi activités" sur la collective fille pour pouvoir lier la collective mère -> peut être faudrait-il enlever ce comportement ?
