### ISSUE TITLE
Un adhérent sur liste d'attente sur une inscription peut s'inscrire sur liste d'attente sur une collective fille

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#619]
L'adhérent Eva est actuellement en liste d'attente sur l'inscription https://collectives.cafannecy.fr/collectives/5402-inscription-ppg-trail-avec-claude-cycle-hiver-2023

L'inscription à la collective https://collectives.cafannecy.fr/collectives/6150-ppg-avec-claude-renforcement-musculaire se fait uniquement sur liste d'attente. Seuls les inscrits de https://collectives.cafannecy.fr/collectives/5402-inscription-ppg-trail-avec-claude-cycle-hiver-2023 devrait pouvoir se mettre sur liste d'attente. Or Eva arrive à se mettre sur liste d'attente

**Comment by gdaviet** [comment]
Effectivement, je vois le bug. Je vais restreindre aux inscriptions "actives"
