### ISSUE TITLE
Liste des événéments à venir / passées vides sur la page Profil encadrant

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#630]
Depuis la maj du site en version 16.0, les 2 tableaux "Sorties encadrées à venir" et "Sorties encadrées passées" ssur la page "Profil encadrant" sont vides.
Exemple https://collectives.cafannecy.fr/profile/organizer/3

**Comment by gdaviet** [comment]
Merci pour le retour, effectivement, il semble y avoir une erreur JS. Je regarde ça
