### ISSUE TITLE
Un jeune E1, E2, J1 ou J2 ne peut pas s'inscrire à un événement de type "Jeunes"

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#650]
Les événements de types "Jeunes" sont limités aux adhérents de catégorie E1, E2, J1 ou J2.

Or lorsqu'un jeune E1, E2, J1 ou J2 tente de s'inscrire sur un événement Jeunes il a le message: 

`Les inscriptions en ligne sont restreintes aux licenses de type J1,J2,E1,E2, ce qui n'est pas votre cas. `

Son inscription lui est refusée.
![image](https://github.com/Club-Alpin-Annecy/collectives/assets/59260805/ccdb042e-b9f0-4829-843b-10491e2fe73f)

Solution de contournement: changer le type d'événement en "Collectives"
![image](https://github.com/Club-Alpin-Annecy/collectives/assets/59260805/1f5635e2-04ba-4e52-b665-48c5ac1977bf)

**Comment by gdaviet** [comment]
Ok je pense que je vois le bug, j'en profiterai pour rajouter un test
