### ISSUE TITLE
Liens cassés sur la popup à la connexion si l'adhérent n'a pas renseigné le numéro de téléphone pour le joindre

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#654]
Lorsqu'un adhérent n'a pas renseigné son numéro de téléphone pour le joindre, une popup informative est affichée lorsqu'il se connecte
![image](https://github.com/Club-Alpin-Annecy/collectives/assets/59260805/a0ba8499-77db-4f2e-8f11-44bf5e7db3a8)

Malheureusement les liens:

- "votre espace personnel FFCAM", https://extranet-clubalpin.com/mesinfos/
- et "ici"

ne sont pas fonctionnels.

Ce texte semble avoir la même source que celui sur la page de profil. Attention donc à bien vérifier qu'il n'y ait pas de régression sur ce message
![image](https://github.com/Club-Alpin-Annecy/collectives/assets/59260805/23afddf4-1b0b-4c4f-8d63-2231036d1a37)

**Comment by gdaviet** [comment]
Merci pour le report, les messages flash contenant du html sont cassés, je vais corriger ca
